### ISSUE TITLE
نحوه عملکرد

### ISSUE THREAD

**Issue by mehrdadmmb2** [SirLordPouya/AntiSpam#1]
سلام
من این نوع نحوه کد زدن رو تاحالا تجربه نکردم
میشه یه توضیح مختصر بدین که الان مثلا کلیک های باتم نویگیشن رو کجا نوشتید و چجوری داره کار میکنه

**Comment by HeyPouya** [comment]
سلام
کلیک ها توسط یکی از لایبراری های مهم گوگل به اسم
Navigation Component
دارن هندل میشن
بهتون پیشنهاد میکنم که حتما در موردش مطالعه کنید.
